import "./globals.css";
import Sidebar from "./component/sidebar/Sidebar";
import Head from "next/head";
import Footer from "./component/footer/footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;1,100;1,300;1,400;1,900&family=Protest+Revolution&family=Roboto:ital,wght@0,100;0,500;0,700;0,900;1,100;1,400;1,500;1,900&display=swap" rel="stylesheet" />
      </Head>
      <body style={{}} className=" ">
        <div style={{}} className="sm:w-[15vw] h-screen sm:flex hidden fixed " >
          <Sidebar />
        </div>

        <div className="sm:w-[85vw] w-full ">

          {children}
       
        </div>
      </body>
    </html>
  );
}
